import Head from "next/head";
import { signIn } from "@/firebase/google";
import { FcGoogle } from "react-icons/fc";
import { useRouter } from "next/router";
import { useAuth } from "@/utils/auth";
import { useEffect } from "react";

/**
 * redirect if user has logged in
 */
const useRedirect = () => {
  const router = useRouter();
  const { user, loading } = useAuth();

  useEffect(() => {
    if (!loading && user) {
      router.push("/workspace");
    }
  }, [loading, user]);

  useEffect(() => {
    router.prefetch("/workspace");
  }, []);
};

export default function Home() {
  useRedirect();
  return (
    <>
      <Head>
        <title>Kanban</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>Welcome</h1>
        <button
          className="w-full border-2 rounded flex items-center justify-center p-1 gap-1.5"
          onClick={signIn}
        >
          <FcGoogle className="text-lg" />
          <div className="text-lg">Continue with Google</div>
        </button>
      </div>
    </>
  );
}
